# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20180802_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=40),
        ),
        migrations.AddField(
            model_name='cart',
            name='itemcost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=40),
        ),
    ]
