# Generated by Django 2.0.5 on 2018-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
