# Generated by Django 2.0.5 on 2018-07-31 20:40

from django.db import migrations, models
import shoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='img',
            field=models.ImageField(null=True, upload_to=shoes.models.upload_img_path, verbose_name='Upload Image'),
        ),
    ]
