# Generated by Django 2.0.5 on 2018-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
