# Generated by Django 2.0.5 on 2018-08-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_shoe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
