# Generated by Django 2.0.5 on 2018-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_auto_20180801_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, default='xyz', unique=True),
        ),
    ]
