# Generated by Django 2.0.5 on 2018-08-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_auto_20180801_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, default='xyz', null=True, unique=True),
        ),
    ]
