# Generated by Django 2.0.5 on 2018-08-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_auto_20180801_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='slug',
        ),
    ]
