# Generated by Django 2.0.5 on 2018-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_auto_20180801_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='nslug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='shoe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
