# Generated by Django 2.0.5 on 2018-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0022_auto_20180801_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
